src/om/core.cljs

`path` is def'ed above, so doesn't need to be included in this `declare`
Resolves #337

Remove declare of already-defined path

---

src/om/core.cljs

Avoid potentially nesting -set-property! calls for the :skip-render-root root
property. Makes it so that changes to the root state done while the root is
being rendered get applied immediately (in the next raf callback).

Fix render bug causing changes to the app state not being reflected

---

.gitignore
project.clj
test/om/tests.cljs

Besides the main point there are two other changes:
* Removed `react.min.js` from the preamble, since it is no longer needed.
* Added source map files `*.map` to `.gitignore` to avoid tracking `scripts/testing.simple.js.map`.
I thought they might be useful, if they are not, I'll resubmit multiple PR's with the desired changes.

Ported om/cursor tests to cljs.test

---

src/main/om/dom.clj

More on `<use>` https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

Added svg use tag to dom.clj

---

src/main/om/next.cljs
src/test/om/next/tests.cljs

Fixes #495
I think this is correct. I'm tracking idents seen as I recursively descent, and I'm tracking which ident is seen by the keyword used at the recursion. This might be overkill (I was originally just using a set, and that works for my tests but it seems like it might be possible to mis-identify a loop if you don't track which ref was crossed at each recursion point).
I also did *not* embed the reference at loop detection: it caused other things to break when I did that because the final tree isn't supposed to have idents in it anymore. Instead, the algorithm puts the looped object in, and stops.

Fixed db->tree so that infinite graph loops are avoided.

---

src/main/om/dom.clj

This PR solves #521.
besides adding missing tags, the `marquee` tag is not supported by React so it was removed. In my tests with `om.dom`, using `dom/marquee` produced the following error: `Uncaught TypeError: React.DOM.marquee is not a function`

OM-521: om.dom is not consistent with React's supported attributes

---

src/main/om/dom.cljs

OM-527: Avoid warning caused by replacing cljs.core/mask

---

src/main/om/next.cljs
src/test/om/next/tests.cljs

My detection of idents seen was accidentally grabbing vectors of idents instead of singles (the loop near the top of db->tree handles the former). Added tests with sample data from @Jannis and verified the fix corrects the issue.
This PR also includes the fix to the `process-roots` tests.
Fixes #529

Fixed db->tree on recursive queries against vectors

---

src/main/om/next.clj

This is a fix for #537.
`~this` will not be bound if using '_' placeholders in lifecycle functions, so we need to use `this#`

OM-537: Uncaught error when using '_' placeholders as the first argument of lifecycle methods

---

src/test/om/next/tests.cljs

I was talking with @noonian on slack and realized there was one more thing to check, so I added a test to prove that union joins are treated properly when you want to promote them to root. This superseded the test labeled om-526, so I replaced that test with the new one.

Added test for treating union as alternate root

---

src/main/om/next.cljs
src/test/om/next/tests.cljs

This is a fix for #539.
- Added a test case which fails without the changes to `var?` and `var->keyword`

OM-539: Using `?namespace/qualified` query params throws error

---

src/main/om/next/server.clj

Fix for #541, add duplicated function from next.cljs for now

OM-541: `dispatch` is missing in om.next.server

---

src/devcards/om/devcards/bugs.cljs
src/main/om/next.cljs

This patch addresses issue #552.
It also adds a devcards example demoing the problem and its solution when the patch is applied.

OM-552: componentWillUpdate doesn't receive correct `next-props`

---

src/devcards/om/devcards/autocomplete.cljs
src/devcards/om/devcards/bugs.cljs
src/devcards/om/devcards/core.cljs
src/devcards/om/devcards/shared_fn_test.cljs
src/devcards/om/devcards/tutorials.cljs
src/main/om/next.cljs

this is a fix for #550.
It removes `mock-root` and updates the devcards examples to use devcards' `dom-node` instead.
The commit message also provides an example of this.

OM-550: drop support for mock-root

---

src/main/om/next.clj

Fixes #569 by setting the React component's displayName as the namespace qualified `defui` name

OM-569: support React's displayName in defui

---

src/main/om/next.cljs
src/test/om/next/tests.cljs

This PR fixes merge-joins, which attempts to merge joins with parameters currently, and should not. Bad behavior will ensue if you promote more than one of the same kind of join with diffrent params, but that is just a user beware kind of thing...nothing much to do about it.
This, combined with the PR from @noonian brings process-roots closer to completion. I think the union part in that PR needs a test around rewrite working.

fixes attempts to merge joins with parameters (which are not mergeable)

---

src/devcards/om/devcards/bugs.cljs
src/main/om/next.cljs

Fixes #595 
Needed change was bringing the `(when-not recursive? ...)` code path inside the `when class` check

OM-595: `index-root` blows the stack when a recursion query is not on its own component

---

src/devcards/om/devcards/bugs.cljs
src/main/om/next.cljs
src/test/om/next/tests.cljs

fixes #598 
- adds devcards example showing the issue to be resolved when the patch is applied
- adds tests

OM-598: `re-index!` should use the mounted instance

---

src/main/om/next.cljs
src/test/om/next/tests.cljs

fixes #615 
- implements custom walking of the query to bind params
- adds tests that verify the expected behavior

OM-615: `bind-query` loses sub-queries metadata

---

src/main/om/next.cljs
src/test/om/next/tests.cljs

This patch is a fix for #612 
- It provides tests that cover both this and #595, which introduced the regression that this patch fixes.

OM-612: `index-root` doesn't follow paths if queries don't have components

---

src/main/om/core.cljs

Fixes the deprecation warning for `om.core/get-node` [#607](https://github.com/omcljs/om/issues/607)

Use ReactDOM.findDOMNode to fix deprecated warning

---

src/main/om/next.cljs

- if components implement `IQuery`, their query must not be nil or empty

Add invariant to `build-index*`

---

src/main/om/next.cljs
src/main/om/next/protocols.cljs

We can't avoid re-querying when setting state because child query params may have changed and the parent will have stale props. I'm going to think about other ways to optimize this, but we can revert my commit to fix master. Sorry.

Revert "optimize set-state! to avoid re-running queries"

---

src/main/om/next.cljs

this is creating a new key under the reconciler's state instead of updating the one it should

[:sends-queued] -> :sends-queued

---

src/main/om/next.clj

I have a performance-sensitive component that renders a large list of items, and it only shows a subset of items in the actual DOM to fill the view. This subset is updated as you scroll to make it appear that everything is loaded in the DOM, when it's actually not.
I noticed that when items outside the view are removed from the DOM (after scrolling), a `reconcile!` and rerender would happen. This happens because the state was being modified in `componentWillUnmount`, but we don't need to modify that state if `om.next/queries` does not have the component instance in it. This optimization avoids unnecessary rerenders, and more importantly unnecessary query execution (modifying the state triggers both).

avoid updating om.next/queries unnecessarily when unmounting

---

src/main/om/next.cljs
src/test/om/next/tests.cljs

`get-dispatch-key` should get the ast's dispatch key for all cases
except when it encounters an ident.

OM-648: Regression in `index-root` for parameterized props

---

src/main/om/next.cljs
src/main/om/next/impl/parser.cljc
src/main/om/util.cljc
src/main/om/util.cljs
src/test/om/next/tests.cljs

This patch introduces modifications to the parser's `path-meta` such
that it uses the query to walk the resulting data structure, leaving
pieces of data not present in the query as they were.
Since some utilities needed by the new `path-meta` were previously
present in the `om.next` namespace, they were moved to `om.util`.

OM-556: Large values in app state slow down transactions

---

src/main/om/util.cljc

because `(identical? '... '...)` produces `false`, switch to using `=`

fix `recursion?` predicate for the :clj branch

---

pom.xml
project.clj

bumps react to 15.0.1
aligns dependency versions between project.clj & pom.xml
also bumps some dependencies with "test" and "provided" scopes to their
latest versions

bump react, deps, align pom.xml and project.clj

---

src/devcards/om/devcards/bugs.cljs
src/main/om/next.cljs
src/test/om/next/tests.cljs

this is the second part of the fix for #679, (first part addressed by PR #680), which makes it such that we support joins deep in union recursive queries.

OM-679: (part 2) support for joins deep in union recursion

---

src/devcards/om/devcards/autocomplete.cljs
src/devcards/om/devcards/bugs.cljs
src/devcards/om/devcards/core.cljs
src/devcards/om/devcards/shared_fn_test.cljs
src/devcards/om/devcards/tutorials.cljs
src/main/om/next.clj
src/main/om/next.cljs

fixes the elision of static methods in Om Next components by the
Closure compiler under advanced compilation.
Related Closure compiler issue:
https://github.com/google/closure-compiler/issues/1776
fix some compilation warnings, remove unused `clojure.walk` require
`devcards.core` also needs to be imported for advanced compilation to
work. It works without in Figwheel because it injects the namespace into
the build.
remove workarounds for advanced compilation in next.cljs

OM-729: emit `@nocollapse` jsdoc for static methods

---

src/devcards/om/devcards/bugs.cljs
src/main/om/next.cljs

- queue the root for re-render whenever the state watch is triggered if
the root class doesn't implement IQuery
- add devcards example
- modify `schedule-render!` to always return boolean
- remove unused check in `reconcile!`

OM-734: Root re-render batching issue

---

src/main/om/next.cljs
src/test/om/next/tests.cljs

also moved the pre-condition for `denormalize*` to `db->tree` so that it
isn't called on every recursive fn call

OM-732: db->tree treats recursion on a join as if it were on a union

---

src/main/om/next/impl/parser.cljc

It's a bit hard to see the changes in the diff, because of indentation, so I'll comment on the diff

OM-760: AST description is incorrect for ParamExprs

---

boot.properties
build.boot
pom.xml
project.clj
resources/public/devcards/main.cljs.edn
src/devcards/om/devcards/core.cljs

- Add a `build.boot` file along with a `boot.properties` and a
`main.cljs.edn` for CLJS compilation
- Bump some deps in `pom.xml` and remove `tools.reader` from
ClojureScript's exclusions, since it now provides 1.0.0-beta3
- Bring `project.clj` to parity with the dependencies in pom.xml

support dev with Boot

---

src/devcards/om/devcards/autocomplete.cljs

Wikipedia doesn't allow empty search queries anymore, so the remote call
will throw an error in that case. This patch changes the behavior of
`search-loop` to only perform the remote call whenever the search query
is not empty.

fix autocompleter devcards example

---

src/main/om/next/impl/parser.cljc
src/test/om/next/tests.cljs

This optimizes the recursive parsing code path by not calling
`path-meta` on these intermediate results. `path-meta` will still be
called after the top-level call returns so the necessary metadata will
be there.

optimize recursive parsing

---

src/main/om/next.cljs
src/test/om/next/tests.cljs

Keeps the fix of `transform-reads` not being destructive, while also
guaranteeing that keys, whether transformed into a query or not, appear
at most once
Fixes #753

OM-753: optimize transform-reads

---

src/main/om/next.cljs

We need to check that the update-path is non-nil, because users might be passing props which don't have path-meta to e.g. components that don't have queries

OM-766: Incremental rendering in reconcile! throws Index out of bounds

---

src/main/om/next.cljc
src/test/om/next/tests.cljc

This affects only the `:clj` branch which was not compliant with how we
allows static methods in ClojureScript.
Also simplify a bit the logic around `defui` for the `:clj` branch

OM-786: Be more permissive for static class methods

---

src/main/om/next.cljc

`react-type` is defined for both :cljs and :clj, but only currently used
for :clj. `type` is used for :cljs instead. This commit simply makes use
of react-type across the board. Fixes #789

Replace react-type related reader conditionals with react-type.

---

src/main/om/next.cljc

Previously, Om was attempting to turn the component into a string, yielding `[Object object]` in the console. The updated message prints the namespaced component name instead.

Using component name for slow query log message

---

src/main/om/dom.cljc

as per the link below, `use` is not present in `React.DOM`. Use
`(js/React.createElement "use")` to create tags not existent in
`React.DOM`.
https://github.com/facebook/react/blob/c78464/src/isomorphic/classic/element/ReactDOMFactories.js

OM-798: remove support for unsupported tags

---

src/devcards/om/devcards/bugs.cljs
src/main/om/dom.cljc
src/main/om/dom.cljs
src/test/om/dom_test.clj

This is useful to create tags not present in `React.DOM` and therefore
not supported as vars in the `om.dom` namespace. Akin to calling
`js/React.createElement`, but more importantly to provide a way to
create these elements when doing server-side rendering, instead of
dropping to low-level functions like `om.dom/element`.

OM-799: Make a new public function, `dom/create-element`

---

src/main/om/next.cljc
src/test/om/next/tests.cljc

Check for vector before mapcat in move-roots. Add test for recursive queries outside of a query root.

process-roots fails when recursive queries are outside of a query-root.

---

src/main/om/next.cljc
src/test/om/next/next_test.clj

fixes #870. Includes the extraction of an inner algorithm that was responsible for getting the protocols and tests. All clj tests pass.

Fixes support for multiple-method statics in defui on the clj side
