omcljs/om

src/main/om/next.cljs
src/test/om/next/tests.cljs

The new process roots and rewrite functionality has the following behavior (verified by tests):
- All top-level non-join elements are preserved
- A join down any path that wants to be at the root is promoted to that position in the top level query. Subroots are not scanned (once one is found along a prefix, it is done with that path)
Major implications/change:
- The top-level query may expand to include more elements than it started with when a common prefix is eliminated for both queries (this is not subroots, these are roots that branch off at a common parent).
Known current weakness:
Two sub-paths could potentially ask the same basic question (see test-process-roots-can-reroot-same-join-from-multiple-paths), which means the single returned result will get rewritten to more than one …

Rewrite of process roots.

---

src/main/om/next.cljs

I think this is correct...it certainly fixes the bug with respect to my application code.

Fix for om-555

---

src/devcards/om/devcards/bugs.cljs
src/main/om/next.cljs
src/test/om/next/tests.cljs

This patch is a fix for #543.
It adds support for union recursion in `tree->db` and `db->tree`, by tracking seen unions so that they can be employed when recursion is seen.
It also adds test cases that cover the new functionality and a devcards
example showing a simple case of recursion within a union.

OM-543: Recursion within a union

---

src/main/om/next.cljs
src/main/om/next/impl/parser.cljc
src/test/om/next/tests.cljs

Adds support for recursion limit syntax

---

src/main/om/next.cljs
src/test/om/next/tests.cljs

Fixes #565.
Adds support for recursion limits in unions
Adds test cases that cover changed functionality
Refactored `db->tree` such that internal arguments are not exposed

OM-565: Recursion limit in unions

---

src/main/om/next.cljs

fixes #574 by using a `query-template` approach

OM-574: Refactor `reduce-query-depth`

---

src/main/om/next.cljs
src/main/om/next/protocols.cljs

As discussed on slack. Seems to work great for me, but I'm still figuring out how to run Om's tests. I thought I'd go ahead and start this discussion though.

optimize set-state! to avoid re-running queries

---

src/main/om/next/impl/parser.cljc
src/test/om/next/tests.cljs

add component meta when converting union ast to query

---

src/main/om/next/impl/parser.cljc

OM-685: optimize `path-meta`

---

src/main/om/next/impl/parser.cljc
src/test/om/next/tests.cljs

OM-714: relax `path-meta` union query inference

---

src/main/om/next.cljs

when rendering incrementally, call `componentWillReceiveProps` on the
component that performed the transaction. Not needed in applications
without queries because they will always re-render from the root, so
React knows to call this method.

OM-536: Situation where componentWillReceiveProps is never called

---

src/main/om/next.clj

Currently only protocols with a single method were able to behave as
static class methods. This patch adds the possibility for protocols with
more than one function to be emitted with the `@nocollapse` JSDoc too.

emit Closure `@nocollapse` for all static protocols

---

src/main/om/next.cljc
src/test/om/next/tests.cljc

OM-772: `key->components` fails to find components indexed by idents in

---

src/main/om/next.cljc
src/test/om/next/tests.cljc

OM-773: `full-query` thinks "No queries exist" when the query path

---

src/main/om/next.cljc
src/test/om/next/tests.cljc

Both are related, but #767 just addressed one part of the issue.
* simplify transform-reads tests
* remove old commented code
* add tests for OM-766 and OM-768

Fix OM-766 and OM-768

---

src/main/om/dom.cljc

as per https://github.com/facebook/react/pull/7582/ and
https://github.com/facebook/react/pull/7519

support "as" and "playsInline" in server-render

---

src/main/om/next/impl/parser.cljc
src/test/om/next/tests.cljc

Support syntax to do a mutation with join data

---

src/devcards/om/devcards/bugs.cljs
src/main/om/next.cljc

See [OM-860](https://github.com/omcljs/om/issues/860)

OM-860 - Use dispatch-key in rendered-path

---

src/main/om/next/impl/parser.cljc
src/test/om/next/tests.cljc

Always unparse on call types

---

src/main/om/next.cljc

Fix Logging in set-query! (easy merge)
